name: Build glshim

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@main

    - name: Build with CI build script
      run: 'cd build/android && $ANDROID_SDK_ROOT/ndk-bundle/ndk-build'

    - name: Upload build output
      uses: actions/upload-artifact@main
      with:
        name: glshim
        path: build/android/libs
