name: Build gl4es
on: [workflow_dispatch]
jobs:
  build-android:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build GL4ES
        run: |
         # wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
         # unzip android-ndk-r26d-linux.zip >> /dev/null
         $ANDROID_NDK_LATEST_HOME/ndk-build APP_PLATFORM=android-24 APP_ABI=arm64-v8a APP_BUILD_SCRIPT=./Android.mk NDK_PROJECT_PATH=.
      - name: Upload GL4ES libs
        uses: actions/upload-artifact@v4
        with:
          name: gl4es-114-android
          path: libs/*
